<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<dict>
  <key>fileTypes</key>
  <array> 
    <string>jakt</string>
   </array>
  <key>name</key>
  <string>Jakt</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Jakt</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(extern)(\s*)(function)((?:[\x{0020}\t\f\b])+)(\w+(?:[\x{0020}\t\f\b])*)(?:(&lt;)((?:(?:[\x{0020}\t\f\b])*(?:\w+)(?:[\x{0020}\t\f\b])*,?)+)(&gt;))?((?:[\x{0020}\t\f\b])*)(\())</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>10</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl_extern</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(function)((?:[\x{0020}\t\f\b])+)(\w+(?:[\x{0020}\t\f\b])*)(?:(&lt;)((?:(?:[\x{0020}\t\f\b])*(?:\w+)(?:[\x{0020}\t\f\b])*,?)+)(&gt;))?((?:[\x{0020}\t\f\b])*)(\())</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\}|;|^)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(extern)?(\s*)(\b(?:class|struct)\b)((?:[\x{0020}\t\f\b])*)(\w+)(?:(&lt;)((?:(?:[\x{0020}\t\f\b])*(?:\w+)(?:[\x{0020}\t\f\b])*,?)+)(&gt;))?((?:[\x{0020}\t\f\b])+)(\{))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>10</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#typedecl</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\benum\b)((?:[\x{0020}\t\f\b])*)(\w+)(?:(&lt;)((?:(?:[\x{0020}\t\f\b])*(?:\w+)(?:[\x{0020}\t\f\b])*,?)+)(&gt;))?((?:[\x{0020}\t\f\b])+)(\{))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enum</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\benum\b)((?:[\x{0020}\t\f\b])*)(\w+)(:))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enum_underlying</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>argument_list</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?=.)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#argument_list__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:(,)|(?=\)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>argument_list__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(\banonymous\b(?:[\x{0020}\t\f\b])*)?(\w+)(:))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#argument_list__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\)|,)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(\bmutable\b)?(\s*)(this)(\s*)(,)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>argument_list__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*$)</string>
          <key>name</key>
          <string>comment.Jakt</string>
        </dict>
       </array>
    </dict>
    <key>enum</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(\w+)((?:[\x{0020}\t\f\b])*)(:\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enum__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|$|(?=\})| )</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\w+)((?:[\x{0020}\t\f\b])*)(\{\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enum__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.function.Jakt</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>enum__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>enum__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#typedecl</string>
        </dict>
       </array>
    </dict>
    <key>enum_underlying</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(\w+)(\s*)(=)(\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enum_underlying__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|$|(?=\}|^))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.function.Jakt</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>enum_underlying__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>expr</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(?:(&quot;)((?:\\.|[^\x{0022}])*)(&quot;))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(&apos;)((?:\\.|\\\d+|[^\x{0027}]))(&apos;))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.character.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(let)((?:[\x{0020}\t\f\b])*)(\bmutable\b)?((?:[\x{0020}\t\f\b])*)(\w+)((?:[\x{0020}\t\f\b])*)(:))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=;|=)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\bas\b)(\s*)((?:!|\?)?)(\s*)(\b(?:truncated|saturated)\b)?(\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=,|$|\}|(?:[\x{0020}\t\f\b])|;)</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\bis\b)(\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=,|$|\}|(?:[\x{0020}\t\f\b])|;)</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(match)((?:[\x{0020}\t\f\b])*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(-?0x[0-9a-fA-F]+)(\w+)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(-?0b[01]+)(\w+)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:(-?\d+(?:\.\d+)?)(\w+)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(==|!=|=|;|!|\(|\)|\{|\}|&amp;&amp;|&amp;|,|\|\||\[|\]|\+|-|\*|/(?!/)|%|\?\?|\?|\!|\+\+|--|\.|&lt;|&gt;|&lt;=|&gt;=|\^|&gt;&gt;|&lt;&lt;|~|\||&lt;&lt;&lt;|&gt;&gt;&gt;|\^=)</string>
          <key>name</key>
          <string>keyword.operator.Jakt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:\b(let|function|while|if|else|return|for|defer|enum|struct|class|match|and|or|not|try|catch|must|throw|continue|break|loop|mutable)\b)</string>
          <key>name</key>
          <string>keyword.Jakt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:\b(unsafe|cpp)\b)</string>
          <key>name</key>
          <string>variable.other.property.Jakt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:\b(this)\b)</string>
          <key>name</key>
          <string>variable.Jakt</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:\b(true|false)\b)</string>
          <key>name</key>
          <string>constant.numeric.Jakt</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:(\w+)((?:[\x{0020}\t\f\b])*)(\())</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[A-Z_]+\b)</string>
          <key>name</key>
          <string>constant.Jakt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.Jakt</string>
        </dict>
       </array>
    </dict>
    <key>expr__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>expr__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>expr__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>expr__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expr__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#match</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>expr__6</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#maybe_named_args</string>
        </dict>
       </array>
    </dict>
    <key>function_decl</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?&lt;=\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#argument_list</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:(\))((?:[\x{0020}\t\f\b])*throws(?:[\x{0020}\t\f\b])*)?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?:[\x{0020}\t\f\b])*-&gt;(?:[\x{0020}\t\f\b])*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=[^\w\x{002a}\[])</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(=&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>function_decl__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>function_decl__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>function_decl__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>function_decl_extern</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?&lt;=\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#argument_list</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:(\))((?:[\x{0020}\t\f\b])*throws(?:[\x{0020}\t\f\b])*)?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?:[\x{0020}\t\f\b])*-&gt;(?:[\x{0020}\t\f\b])*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#function_decl_extern__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=[^\w\x{002a}\[])</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>function_decl_extern__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>match</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#match__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>match__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(=&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#match__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>match__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>maybe_named_args</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(\s*)(\w+)(:)(\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.Jakt</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#maybe_named_args__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|(?=\)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#maybe_named_args__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|(?=\)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>maybe_named_args__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>maybe_named_args__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>type</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#type__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:\b(raw|weak|mutable)\b)((?:[\x{0020}\t\f\b])*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#type__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:^|(?=[^\x{003c}\x{003f}\w\x{002a}\[\x{0020}]))</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#type__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:^|(?=[^\x{003c}\x{003f}\w\[\x{0020}]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>type__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>type__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>type__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.type.Jakt</string>
          <key>end</key>
          <string>(?:)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#type__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>type__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>type__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type_list</string>
        </dict>
       </array>
    </dict>
    <key>type_list</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((?:[\x{0020}\t\f\b])*(,|(?:[\x{0020}\t\f\b])*)(?:[\x{0020}\t\f\b])*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#type_list__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=&gt;|,)</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>type_list__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
    <key>typedecl</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?:(\w+)(:\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.Jakt</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#typedecl__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,| |^|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Jakt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>typedecl__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
